global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'prometheus-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']

  # https://prometheus.io/docs/prometheus/latest/configuration/configuration/#file_sd_config
  - job_name: 'file-based-discovery'
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets.d/*.yml'
        - '/etc/prometheus/targets.d/*.yaml'
        - '/etc/prometheus/targets.d/*.json'
        refresh_interval: 5m
